### ISSUE TITLE
是否和官网NVIDIA DRIVE® OS 6.0.10一模一样的，可以直接在orin 芯片板卡上面部署

### ISSUE THREAD

**Issue by chinamaoge** [ZhenshengLee/nv_driveos#1]

**Comment by chinamaoge** [comment]
我是因为在NVIDIA 官网无法下载对应的drive os，所以才在github上面来找可以安装的版本

**Comment by chinamaoge** [comment]
如果你能提供我想知道的内容 ， 非常感谢你的回复

**Comment by ZhenshengLee** [comment]
docker images is private, please contact your NVIDIA representive for more details.

The content of this repo is a little part of the driveos docker image, and should only be for learning and bug sharing.
